openapi: "3.0.0"
info:
  version: 1.0.0
  title: Generate models 
paths:
  /client:
    get:
      operationId: getClient
      responses:
        200: 
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/ClientType"
    put:
      operationId: updateClient
      responses:
        400: 
          content:
            application/json:
              schema: 
                type: object
                properties:
                  code:
                    type: string
                required:
                - code 
components:
  schemas:
    ClientType:
      type: object
      required:
        - name 
      properties:
        name:
          type: string
    Unreferenced:
      type: object
      required:
        - id 
      properties:
        id: 
          type: integer