// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ObjError Standard error
type ObjError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

// ObjUser Representation of user
type ObjUser struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	TgChatId  *int64  `json:"tg_chat_id,omitempty"`
	TgId      *int64  `json:"tg_id,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// RespCreateUser defines model for RespCreateUser.
type RespCreateUser struct {
	Data struct {
		// UserId Unique user identifier (UUID)
		UserId openapi_types.UUID `json:"user_id"`
	} `json:"data"`
}

// RespError defines model for RespError.
type RespError struct {
	// Error Standard error
	Error ObjError               `json:"error"`
	Meta  map[string]interface{} `json:"meta"`
}

// RespGetUser defines model for RespGetUser.
type RespGetUser struct {
	// Data Representation of user
	Data ObjUser `json:"data"`
}

// RespUpdateUser defines model for RespUpdateUser.
type RespUpdateUser struct {
	// Data Representation of user
	Data ObjUser `json:"data"`
}

// ReqCreateUser defines model for ReqCreateUser.
type ReqCreateUser struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	TgChatId  int64   `json:"tg_chat_id"`
	TgId      int64   `json:"tg_id"`
	Username  *string `json:"username,omitempty"`
}

// ReqUpdateUser defines model for ReqUpdateUser.
type ReqUpdateUser struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	TgChatId  *int64  `json:"tg_chat_id,omitempty"`
	TgId      *int64  `json:"tg_id,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// V1CreateUserJSONBody defines parameters for V1CreateUser.
type V1CreateUserJSONBody struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
	TgChatId  int64   `json:"tg_chat_id"`
	TgId      int64   `json:"tg_id"`
	Username  *string `json:"username,omitempty"`
}

// V1CreateUserJSONRequestBody defines body for V1CreateUser for application/json ContentType.
type V1CreateUserJSONRequestBody V1CreateUserJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// V1CreateUserWithBody request with any body
	V1CreateUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	V1CreateUser(ctx context.Context, body V1CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// V1GetUser request
	V1GetUser(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// V1UpdateUser request
	V1UpdateUser(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) V1CreateUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewV1CreateUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) V1CreateUser(ctx context.Context, body V1CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewV1CreateUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) V1GetUser(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewV1GetUserRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) V1UpdateUser(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewV1UpdateUserRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewV1CreateUserRequest calls the generic V1CreateUser builder with application/json body
func NewV1CreateUserRequest(server string, body V1CreateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewV1CreateUserRequestWithBody(server, "application/json", bodyReader)
}

// NewV1CreateUserRequestWithBody generates requests for V1CreateUser with any type of body
func NewV1CreateUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewV1GetUserRequest generates requests for V1GetUser
func NewV1GetUserRequest(server string, id UserId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewV1UpdateUserRequest generates requests for V1UpdateUser
func NewV1UpdateUserRequest(server string, id UserId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// V1CreateUserWithBodyWithResponse request with any body
	V1CreateUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*V1CreateUserResponse, error)

	V1CreateUserWithResponse(ctx context.Context, body V1CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*V1CreateUserResponse, error)

	// V1GetUserWithResponse request
	V1GetUserWithResponse(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*V1GetUserResponse, error)

	// V1UpdateUserWithResponse request
	V1UpdateUserWithResponse(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*V1UpdateUserResponse, error)
}

type V1CreateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RespCreateUser
	JSONDefault  *RespError
}

// Status returns HTTPResponse.Status
func (r V1CreateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r V1CreateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type V1GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RespGetUser
	JSONDefault  *RespError
}

// Status returns HTTPResponse.Status
func (r V1GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r V1GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type V1UpdateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RespUpdateUser
	JSONDefault  *RespError
}

// Status returns HTTPResponse.Status
func (r V1UpdateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r V1UpdateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// V1CreateUserWithBodyWithResponse request with arbitrary body returning *V1CreateUserResponse
func (c *ClientWithResponses) V1CreateUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*V1CreateUserResponse, error) {
	rsp, err := c.V1CreateUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseV1CreateUserResponse(rsp)
}

func (c *ClientWithResponses) V1CreateUserWithResponse(ctx context.Context, body V1CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*V1CreateUserResponse, error) {
	rsp, err := c.V1CreateUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseV1CreateUserResponse(rsp)
}

// V1GetUserWithResponse request returning *V1GetUserResponse
func (c *ClientWithResponses) V1GetUserWithResponse(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*V1GetUserResponse, error) {
	rsp, err := c.V1GetUser(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseV1GetUserResponse(rsp)
}

// V1UpdateUserWithResponse request returning *V1UpdateUserResponse
func (c *ClientWithResponses) V1UpdateUserWithResponse(ctx context.Context, id UserId, reqEditors ...RequestEditorFn) (*V1UpdateUserResponse, error) {
	rsp, err := c.V1UpdateUser(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseV1UpdateUserResponse(rsp)
}

// ParseV1CreateUserResponse parses an HTTP response from a V1CreateUserWithResponse call
func ParseV1CreateUserResponse(rsp *http.Response) (*V1CreateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &V1CreateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RespCreateUser
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RespError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseV1GetUserResponse parses an HTTP response from a V1GetUserWithResponse call
func ParseV1GetUserResponse(rsp *http.Response) (*V1GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &V1GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RespGetUser
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RespError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseV1UpdateUserResponse parses an HTTP response from a V1UpdateUserWithResponse call
func ParseV1UpdateUserResponse(rsp *http.Response) (*V1UpdateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &V1UpdateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RespUpdateUser
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest RespError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
