openapi: "3.0.0"
info: 
  version: 1.0.0
  title: Minimal ping API servers
paths:
  /ping:
    get:
      operationId: ping
      responses:
        '200':
          description: pet responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
components:
  schemas:
    Pong:
      type: object
      required:
        - ping
      properties:
        ping: 
          type: string
          example: pong